### ISSUE TITLE
LXD, Node configuration train though and doubts

### ISSUE THREAD

**Issue by ralexrdz** [vientos/vientos-deploy#18]
If I would like to add a new container for Autogestival app I would need to
1.  add an other children to inventory.hosts.yml
```
all:
  children:
    mx:
      children:
        ...
        mx-autogestival
          hosts:
            staging.vientos.coop:
              ansible_host: 162.247.75.214
              ansible_port: 5282
              ansible_python_interpreter: /usr/bin/python3
        
```

2. An other folder in inventory/host_vars/convocatoria.autogestival/config.yml
```
common:
env: production
app:
  name: app
  domain: convocatoria.autogestival.org
``` 
3. provision.yml should also include nginx and mongodb and should import repo from github.com/Autogestival/convocatoria-2018

 4. deploy.yml should have npm install and service start

4. ¿Create LXD container?, here is where I don't know exactly what it should contain or which file is the conf

5. Once in my container add to /etc/nginx/sites-enabled/convocatoria.conf // similar to idp
